# Argument for ROS
ARG version
ARG bundles

# ROS image
From osrf/ros:$version-$bundles

# Argument for user
ARG USER
ARG uid
# User part
ADD ./.create_user /home/
RUN sudo bash /home/.create_user $USER $uid
RUN rm -f /home/.create_user

# For Intel
RUN sudo apt update
RUN apt install libgl1-mesa-glx libgl1-mesa-dri -y
RUN rm -rf /var/lib/apt/lists/*

# update and basic pkgs
RUN sudo apt update
RUN sudo apt install -y \
    apt-utils debconf-utils \
    mesa-utils git vim wget \
    ca-certificates lsb-release gnupg2 curl \
    net-tools iputils-ping software-properties-common
RUN DEBIAN_FRONTEND=noninteractive apt install xserver-xorg-video-intel -y


############### You can change this part #######################
# Additional ROS packages
RUN sudo apt install -y \
              ros-$ROS_DISTRO-gazebo-* \
              ros-$ROS_DISTRO-velocity-controllers \
              ros-$ROS_DISTRO-effort-controllers \
              ros-$ROS_DISTRO-joint-* \
              ros-$ROS_DISTRO-tf* \
              ros-$ROS_DISTRO-rosbridge-* \
              ros-$ROS_DISTRO-hardware* \
              ros-$ROS_DISTRO-con* \
              ros-$ROS_DISTRO-cv* \
              ros-$ROS_DISTRO-rviz*

# Python package for ROS
RUN sudo apt install protobuf-compiler protobuf-c-compiler -y
RUN sudo apt install python3-opencv -y
RUN sudo apt install python3-pip -y
RUN sudo apt install libgmp-dev python3-dev -y

################################################################

# Dependencies
RUN sudo apt install libboost-all-dev -y
RUN sudo apt install libyaml-cpp* -y
RUN sudo apt install libeigen3-dev -y
RUN sudo apt upgrade libomp-dev -y
RUN sudo apt install doctest* -y
RUN sudo apt install gdb -y
RUN sudo apt install clang-format -y

###############################################################

# copy files
ADD ./.ps.txt /home/$USER/
ADD ./.ros_source.txt /home/$USER/
ADD ./.separate_install /home/$USER/

# source ros and your workspace
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /home/$USER/.bashrc
RUN cat /home/$USER/.ps.txt >> /home/$USER/.bashrc
RUN cat /home/$USER/.ros_source.txt >> /home/$USER/.bashrc

# install by different ROS distribution
RUN sudo bash /home/$USER/.separate_install -d $ROS_DISTRO -u $USER
RUN sudo rm -rf /home/$USER/.ros_source.txt /home/$USER/.ps.txt /home/$USER/.separate_install

USER $USER
# upgrade all package for the last time
RUN sudo apt update && sudo apt upgrade -y