name: Test ros-contr
on:
  push:
    branches: [ main ]

jobs:
  Install_ros-contr:
    name: Install the ros-contr
    runs-on: ubuntu-latest
    steps:
      - name: Test installation
        shell: bash
        uses: actions/checkout@main
        run: bash ./install.sh