name: Test ROS Container
on:
  push:
    branches: [ main ]

jobs:
  Install_ros-contr:
    name: Install the ros_contr
    runs-on: ubuntu-latest
    steps:
      - name: Main brach
        uses: actions/checkout@main
      - name: Move folder
        run: mv /home/$USER/work/ros_container/ros_container /home/$USER/
      - name: Test installation
        shell: bash
        run: cd /home/$USER/ros_container && bash ./install.sh test
      - name: Build ros humble
        run: ros_contr build -y
      - name: Run ros_contr
        run: ros_contr -w test