name: Test ROS CNTR
on:
  push:
    branches: [ main ]

jobs:
  Install_ros-cntr:
    name: Install the ros_cntr
    runs-on: ubuntu-latest
    steps:
      - name: Main brach
        uses: actions/checkout@main
      - name: Test installation
        shell: bash
        run: bash ./install.sh
      - name: Show config
        run: ros_cntr config show
      # - name: Build ros humble
      #   run: ros_cntr build -y
      # - name: Run ros_cntr
      #   run: ros_cntr -w test