name: Test ROS Container
on:
  push:
    branches: [ main ]

jobs:
  Install_ros-contr:
    name: Install the ros_contr
    runs-on: ubuntu-latest
    steps:
      - name: Main brach
        uses: actions/checkout@main
      - name: Test installation
        shell: bash
        run: bash ./install.sh
      - name: Build ros humble
        run: ros_contr build -y
      - name: Make test_ws
        run: mkdir -p /home/$USER/ROS/humble/test_ws/src